# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52ef995bf96d8b282227eed82fc87f727b8fe3ee64a80740437cc1d2c6f79573b4da791ed1d38d4c4a45c81a1c3e8f9264e4256d861538fe1ed84e499040b9d2

test:
  secret_key_base: e819747046673966ebd86dd5e4d432ead7815966203990a32f0d3a1073d899eb5ee9b878f169f830f87ba752c258834d229ed6c0defe7fa29b15233d0570b1e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
